### ISSUE TITLE
review form post

### ISSUE THREAD

**Issue by stevemao** [stevemao/javascript-cant-replace-html#2]
Looks like FormData only works with ajax? I'm not so sure what Content-Type is supported. I think `HTMLFormElement.submit()` is doing something different.

cc @tarungarg546

**Comment by tarungarg546** [comment]
Citing MDN here again .

> The transmitted data is in the same format that the form's submit() method would use to send the data if the form's encoding type were set to multipart/form-data.

Also there is article on MDN article about how to submit forms using only [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Submitting_forms_and_uploading_files) .

And yes, this seems to be true that `FormData` only works with ajax.
